name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build
      - run: git add -f dist/
      - run: |
          git config --global user.email "connorturlan@users.noreply.github.com"
          git config --global user.name "Connor Turlan"
      - run: git commit -m "pages deploy"
      - run: git push origin main:gh-pages

    #   - name: Deploy
    #     uses: crazy-max/ghaction-github-pages@v3
    #     with:
    #       target_branch: gh-pages
    #       build_dir: dist
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
